version: '2'

services:

  hello-test:
    image: busybox
    command: ['/bin/sh', '-c', 'while true; do echo hello world; sleep 10; done']

  logspout:
    image: gliderlabs/logspout:v3.2.4
    command: syslog://logstash:5000
    environment:
      - RETRY_COUNT=100
    links:
      - logstash
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.0
    environment:
      - LOGSPOUT=ignore
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    environment:
      - LOGSPOUT=ignore
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - LOGSPOUT=ignore
      - node.name=dev-log-kibana
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  elasticsearch_old_index_deletion:
    build: ./elasticsearch_old_index_deletion

